version: '3.8'

services:

  mysql1:
    image: mysql:latest
    volumes:
      - mysql1:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_1
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    expose:
      - 3307
    networks:
      - sales-company-network

  mysql2:
    image: mysql:latest
    volumes:
      - mysql2:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_2
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    expose:
      - 3308
    networks:
      - sales-company-network


  eureka-server:
    image: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: always
    networks:
      - sales-company-network

  users-service:
    image: users-service
    build:
      context: ./users-service
      dockerfile: Dockerfile
    ports:
      - "8200"
    restart: always
    networks:
      - sales-company-network

  products-service:
    image: products-service
    build:
      context: ./products-service
      dockerfile: Dockerfile
    ports:
      - "8300"
    restart: always
    networks:
      - sales-company-network

volumes:
  mysql1:
  mysql2:

networks:
  sales-company-network: