version: '3.8'

services:

  mysql1:
    image: mysql:latest
    volumes:
      - mysql1:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_1
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    expose:
      - 3307
    networks:
      - sales-company-network

  mysql2:
    image: mysql:latest
    volumes:
      - mysql2:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_2
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    expose:
      - 3308
    networks:
      - sales-company-network

  mysql3:
    image: mysql:latest
    volumes:
      - mysql3:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_3
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      MYSQL_TCP_PORT: 3309
    ports:
      - "3309:3309"
    expose:
      - 3309
    networks:
      - sales-company-network

  mysql4:
    image: mysql:latest
    volumes:
      - mysql4:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_4
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      MYSQL_TCP_PORT: 3310
    ports:
      - "3310:3310"
    expose:
      - 3310
    networks:
      - sales-company-network


  eureka-server:
    image: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: always
    networks:
      - sales-company-network

  user-service:
    image: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8200"
    restart: always
    networks:
      - sales-company-network

  product-service:
    image: product-service
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8300"
    restart: always
    networks:
      - sales-company-network

  order-service:
    image: order-service
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8400"
    restart: always
    networks:
      - sales-company-network

  shop-service:
    image: shop-service
    build:
      context: ./shop-service
      dockerfile: Dockerfile
    ports:
      - "8500"
    restart: always
    networks:
      - sales-company-network

  config-server:
    image: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    restart: always
    networks:
      - sales-company-network


  api-gateway:
    image: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - sales-company-network


volumes:
  mysql1:
  mysql2:
  mysql3:
  mysql4:

networks:
  sales-company-network: