server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8200
          predicates:
            - Path=/users/**
          filters:
            # Np ponizszy filter dodaje do kazdego request naglowek ktory tutaj przekazesz
            - AddRequestHeader=X-Request-red, blue
        - id: product-service
          uri: http://book-service:8300
          predicates:
            - Path=/products/**
        - id: order-service
          uri: http://order-service:8400
          predicates:
            - Path=/orders/**
        - id: shop-service
          uri: http://shop-service:8500
          predicates:
            - Path=/shops/**

# Dorzucamy loggery od api gateway
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
