server:
  port: 8200

spring:
  application:
    name: users-service
  config:
    import: optional:configserver:http://config-server:8888/
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true