server:
  port: 8400

spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://config-server:8888/
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
      fetch-registry: true
  instance:
    prefer-ip-address: true