server:
  port: 8300

spring:
  application:
    name: order-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3308/db_2?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.jdbc.Driver
    username: user
    password: user1234

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true