spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/szymon-sawicki/sales-company-configs
          default-label: main
  application:
    name: spring-cloud-config-server
server:
  port: 8888