spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kmprograms/microservices-sroda
          # password:
          # username:
  application:
    name: spring-cloud-config-server
server:
  port: 8888